// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SimplArchive.TestModule;

#nullable disable

namespace SimplArchive.TestModule.Migrations
{
    [DbContext(typeof(TestReadModelContext))]
    [Migration("20260904181919_InitialLandingCounters")]
    partial class InitialLandingCounters
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SimplArchive.TestModule.TestLandingCounter", b =>
                {
                    b.Property<Guid>("DossierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.HasKey("DossierId");

                    b.ToTable("tm_landing_counters", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
