using SimplArchive.Domain.Documents;

namespace SimplArchive.Infrastructure.Conversion;

// Copies a source version's annotations onto a searchable-PDF successor version (SearchablePdfWorker, ADR 0527).
// The successor becomes the current version, so without carrying the annotations forward an annotated source
// (e.g. an imported TIFF, ADR 0527) would appear to lose them. The PDF is the same page images with an OCR text
// layer, so page index + normalized geometry transfer 1:1; author/date/kind/colour/points are all preserved.
public static class AnnotationCarryOver
{
    // Builds the successor's copy of an annotation: everything is carried except the identity/version anchor
    // (a fresh Id, the successor's version id) and ConcurrencyToken (regenerated by SaveChanges). Guarded by
    // AnnotationCarryOverTests so a newly-added annotation field can't be silently dropped on conversion.
    public static DocumentAnnotation ForSuccessorVersion(DocumentAnnotation source, Guid successorVersionId) => new()
    {
        Id = Guid.NewGuid(),
        TenantId = source.TenantId,
        DocumentId = source.DocumentId,
        DocumentVersionId = successorVersionId,
        PageIndex = source.PageIndex,
        Kind = source.Kind,
        PositionX = source.PositionX,
        PositionY = source.PositionY,
        Width = source.Width,
        Height = source.Height,
        Points = source.Points,
        Text = source.Text,
        Color = source.Color,
        CreatedByUserId = source.CreatedByUserId,
        CreatedByServiceAccountId = source.CreatedByServiceAccountId,
        CreatedAt = source.CreatedAt,
        UpdatedAt = source.UpdatedAt,
    };
}
