using System.Reflection;
using SimplArchive.Domain.Documents;
using SimplArchive.Infrastructure.Conversion;

namespace SimplArchive.UnitTests;

// Guards AnnotationCarryOver.ForSuccessorVersion (SearchablePdfWorker, ADR 0527): when the auto TIFF/scan →
// searchable-PDF conversion creates a successor version, the source version's annotations are copied onto it so
// they aren't lost (the successor becomes the current version). A reflection sweep asserts *every* annotation
// property is carried over except the three that must change — so a newly-added field can't be silently dropped.
public class AnnotationCarryOverTests
{
    // Re-anchored to the successor (fresh Id + version) or regenerated by SaveChanges — must NOT equal the source.
    private static readonly HashSet<string> Reset =
        [nameof(DocumentAnnotation.Id), nameof(DocumentAnnotation.DocumentVersionId), nameof(DocumentAnnotation.ConcurrencyToken)];

    [Fact]
    public void Copies_every_field_except_id_version_and_concurrency_token()
    {
        var successorVersionId = Guid.NewGuid();
        var source = new DocumentAnnotation
        {
            Id = Guid.NewGuid(),
            TenantId = Guid.NewGuid(),
            DocumentId = Guid.NewGuid(),
            DocumentVersionId = Guid.NewGuid(),
            PageIndex = 2,
            Kind = AnnotationKind.Freehand,
            PositionX = 0.42,
            PositionY = 0.17,
            Width = 0.3,
            Height = 0.25,
            Points = "0.10,0.20 0.11,0.22",
            Text = "carry me",
            Color = "#FF8C8C",
            CreatedByUserId = Guid.NewGuid(),
            CreatedByServiceAccountId = null,
            CreatedAt = new DateTimeOffset(2016, 10, 20, 14, 29, 0, TimeSpan.Zero),
            UpdatedAt = new DateTimeOffset(2016, 10, 21, 9, 0, 0, TimeSpan.Zero),
            ConcurrencyToken = Guid.NewGuid(),
        };

        var copy = AnnotationCarryOver.ForSuccessorVersion(source, successorVersionId);

        Assert.NotEqual(source.Id, copy.Id);
        Assert.Equal(successorVersionId, copy.DocumentVersionId);

        foreach (var prop in typeof(DocumentAnnotation).GetProperties(BindingFlags.Public | BindingFlags.Instance))
        {
            if (Reset.Contains(prop.Name))
            {
                continue;
            }

            Assert.Equal(prop.GetValue(source), prop.GetValue(copy));
        }
    }
}
