using System.Buffers.Binary;
using System.IO.Compression;

namespace SimplArchive.UnitTests;

/// <summary>
/// The committed macOS <c>.icns</c> is on Apple's icon grid, and carries no chunk type that renders as noise
/// (issue #787).
/// </summary>
/// <remarks>
/// <para>
/// The <c>.icns</c> is a checked-in <b>binary</b>, regenerated by <c>--gen-icons</c>. A regeneration that
/// silently reverted either property would show no reviewable diff at all — so the same measurement that found
/// the bug is what has to guard it. Both defects here were invisible to every existing check: the file was
/// structurally perfect throughout, with all ten representations present, square and correctly sized.
/// </para>
/// <para>
/// The PNG is decoded by hand rather than with an imaging package. Only the alpha channel is needed, .NET
/// ships the inflate (<see cref="ZLibStream"/>), and the alternative is a dependency in the fast tier for one
/// assertion.
/// </para>
/// </remarks>
public class MacOsIconGridTests
{
    private const string Icns = "src/SimplArchive.DesktopClient/Assets/SimplArchive.icns";

    // Apple's grid: the tile is 824 on a 1024 canvas (~80%), the shadow hanging into the padding below.
    // Measured on real icons — Notes and Reminders 214/256, Affinity Designer 850/1024.
    private const double MinFill = 0.76;
    private const double MaxFill = 0.88;

    [Fact]
    public void The_macos_icon_is_inset_on_apples_grid_with_the_shadow_below()
    {
        var chunks = Chunks(File.ReadAllBytes(Path.Combine(RepoPaths.Root(), Icns)));
        var largest = chunks.OrderByDescending(c => c.Size).First();
        var (width, height, alpha) = DecodeAlpha(largest.Payload);

        // TWO bounding boxes, because the tile and its shadow live at different alphas and the assertions are
        // about different things. A single box measured above the shadow reports the tile as perfectly
        // symmetric — which it is — and says nothing at all about whether a shadow was drawn.
        var tile = Bounds(width, height, alpha, threshold: 200);
        var withShadow = Bounds(width, height, alpha, threshold: 8);

        // The defect this replaces: the tile filled the canvas edge to edge, so in /Applications it drew at
        // roughly 1.5x the AREA of every neighbour.
        var fill = (tile.Right - tile.Left + 1) / (double)width;
        Assert.InRange(fill, MinFill, MaxFill);

        // …and the SHADOW, which is the half an inset alone does not give. It must fall BELOW the tile — which
        // is why real icons measure more padding above than below (Affinity Designer: T97 B77). Asserting this
        // separately matters: when the shadow was a DropShadowEffect it did not render at all, because effects
        // are applied by the composition renderer and never reach RenderTargetBitmap. Nothing failed, nothing
        // warned, and the inset assertion above passed regardless.
        Assert.True(withShadow.Bottom > tile.Bottom,
            $"expected a shadow below the tile: tile ends at y={tile.Bottom}, anything visible ends at y={withShadow.Bottom}");
    }

    [Fact]
    public void No_chunk_type_renders_the_icon_as_noise()
    {
        var chunks = Chunks(File.ReadAllBytes(Path.Combine(RepoPaths.Root(), Icns)));

        // `icp4`/`icp5` predate PNG-in-ICNS and overlap the raw-pixel formats, so readers draw their payload as
        // ARGB PIXELS. Our valid PNG bytes were rendered as random colour noise at 16px and 32px, at alpha 1.0
        // everywhere, while every larger size was fine. Apple's own icons do not use them.
        var ambiguous = chunks.Where(c => c.Type is "icp4" or "icp5").Select(c => c.Type).ToList();
        Assert.True(ambiguous.Count == 0,
            $"the icns carries {string.Join(", ", ambiguous)}, whose payload readers interpret as raw pixels — "
            + "the 16px and 32px representations will render as noise. macOS downscales from ic11 instead.");

        Assert.NotEmpty(chunks);
        Assert.All(chunks, c => Assert.True(
            c.Payload.Length > 8 && c.Payload[..8].SequenceEqual(new byte[] { 0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A }),
            $"chunk {c.Type} is not a PNG"));
    }

    private record Chunk(string Type, int Size, byte[] Payload);

    private static List<Chunk> Chunks(byte[] icns)
    {
        Assert.Equal("icns", System.Text.Encoding.ASCII.GetString(icns, 0, 4));
        var chunks = new List<Chunk>();
        var i = 8;
        while (i + 8 <= icns.Length)
        {
            var type = System.Text.Encoding.ASCII.GetString(icns, i, 4);
            var length = (int)BinaryPrimitives.ReadUInt32BigEndian(icns.AsSpan(i + 4, 4));
            if (length < 8 || i + length > icns.Length)
            {
                break;
            }

            var payload = icns[(i + 8)..(i + length)];
            var size = payload.Length > 24 ? (int)BinaryPrimitives.ReadUInt32BigEndian(payload.AsSpan(16, 4)) : 0;
            chunks.Add(new Chunk(type, size, payload));
            i += length;
        }

        return chunks;
    }

    /// <summary>Decodes an 8-bit RGBA PNG's alpha channel. Enough for a bounding box, and nothing more.</summary>
    private static (int Width, int Height, byte[] Alpha) DecodeAlpha(byte[] png)
    {
        var width = (int)BinaryPrimitives.ReadUInt32BigEndian(png.AsSpan(16, 4));
        var height = (int)BinaryPrimitives.ReadUInt32BigEndian(png.AsSpan(20, 4));
        Assert.Equal(8, png[24]);   // bit depth
        Assert.Equal(6, png[25]);   // colour type: truecolour with alpha

        using var compressed = new MemoryStream();
        var i = 8;
        while (i + 8 <= png.Length)
        {
            var length = (int)BinaryPrimitives.ReadUInt32BigEndian(png.AsSpan(i, 4));
            var type = System.Text.Encoding.ASCII.GetString(png, i + 4, 4);
            if (type == "IDAT")
            {
                compressed.Write(png, i + 8, length);
            }

            i += 12 + length;
            if (type == "IEND")
            {
                break;
            }
        }

        compressed.Position = 0;
        using var inflate = new ZLibStream(compressed, CompressionMode.Decompress);
        using var raw = new MemoryStream();
        inflate.CopyTo(raw);
        var data = raw.ToArray();

        // Un-filter, per PNG spec §9. Bpp is 4 (RGBA8).
        const int bpp = 4;
        var stride = width * bpp;
        var alpha = new byte[width * height];
        var previous = new byte[stride];
        var current = new byte[stride];
        for (var y = 0; y < height; y++)
        {
            var offset = y * (stride + 1);
            var filter = data[offset];
            Array.Copy(data, offset + 1, current, 0, stride);
            for (var x = 0; x < stride; x++)
            {
                int a = x >= bpp ? current[x - bpp] : 0, b = previous[x], c = x >= bpp ? previous[x - bpp] : 0;
                current[x] = filter switch
                {
                    1 => (byte)(current[x] + a),
                    2 => (byte)(current[x] + b),
                    3 => (byte)(current[x] + (a + b) / 2),
                    4 => (byte)(current[x] + Paeth(a, b, c)),
                    _ => current[x],
                };
            }

            for (var x = 0; x < width; x++)
            {
                alpha[(y * width) + x] = current[(x * bpp) + 3];
            }

            (previous, current) = (current, previous);
            Array.Copy(previous, current, stride);
        }

        return (width, height, alpha);
    }

    private static byte Paeth(int a, int b, int c)
    {
        int p = a + b - c, pa = Math.Abs(p - a), pb = Math.Abs(p - b), pc = Math.Abs(p - c);
        return (byte)(pa <= pb && pa <= pc ? a : pb <= pc ? b : c);
    }

    /// <summary>Bounding box of everything at or above <paramref name="threshold"/> alpha.</summary>
    private static (int Left, int Top, int Right, int Bottom) Bounds(int width, int height, byte[] alpha, byte threshold)
    {
        int left = width, top = height, right = -1, bottom = -1;
        for (var y = 0; y < height; y++)
        {
            for (var x = 0; x < width; x++)
            {
                if (alpha[(y * width) + x] < threshold)
                {
                    continue;
                }

                if (x < left) { left = x; }
                if (x > right) { right = x; }
                if (y < top) { top = y; }
                if (y > bottom) { bottom = y; }
            }
        }

        Assert.True(right >= 0, "the icon has no opaque pixels at all");
        return (left, top, right, bottom);
    }

}
