using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SimplArchive.Domain.CalDav;
using SimplArchive.Domain.Documents;
using SimplArchive.Domain.Tenants;

namespace SimplArchive.Infrastructure.Persistence.Configurations;

// See ADR 0622. The identity PK IS the sync sequence, so it must be generated by the store and never set by
// hand. (FolderId, Id) backs both questions asked of this table: a collection's CTag (its highest id) and
// "everything since N". Cascade from the folder — a purged collection's log goes with it.
public class DavCollectionChangeConfiguration : IEntityTypeConfiguration<DavCollectionChange>
{
    public void Configure(EntityTypeBuilder<DavCollectionChange> builder)
    {
        builder.HasKey(c => c.Id);
        builder.Property(c => c.Id).ValueGeneratedOnAdd();
        builder.Property(c => c.ResourceName).IsRequired().HasMaxLength(512);
        builder.Property(c => c.ChangeType).HasConversion<int>();

        builder.HasIndex(c => new { c.FolderId, c.Id });

        builder.HasOne<Tenant>().WithMany().HasForeignKey(c => c.TenantId).OnDelete(DeleteBehavior.Restrict);
        builder.HasOne<Document>().WithMany().HasForeignKey(c => c.FolderId).OnDelete(DeleteBehavior.Cascade);
    }
}
