#!/usr/bin/env bash
# Regenerates docker-compose.imap.yml so the IMAP listener serves Caddy's CURRENT Let's Encrypt certificate.
#
# Why generated rather than written once: the app takes the certificate as PEM CONTENT (Imap__CertificatePem),
# not a path, so an inlined copy would keep serving the old cert after Caddy renews (~60 days) and clients
# would start refusing the connection. reset.sh runs this first, so every daily reset re-reads what Caddy holds.
#
# Why a TRUSTED cert matters: Apple's Internet Accounts framework silently refuses plaintext IMAP, and appears
# to silently reject untrusted self-signed certs too — no error is shown, the account simply never syncs.
set -euo pipefail
cd "$(dirname "$0")"

DOMAIN=demo.simplarchive.dev
CERT=$(ls caddy_data/caddy/certificates/*/"$DOMAIN"/"$DOMAIN".crt 2>/dev/null | head -1)
KEY=$(ls caddy_data/caddy/certificates/*/"$DOMAIN"/"$DOMAIN".key 2>/dev/null | head -1)

if [ -z "${CERT:-}" ] || [ -z "${KEY:-}" ]; then
  echo "No Caddy certificate for $DOMAIN yet — writing an override WITHOUT IMAP (the stack still comes up)."
  printf 'services:\n  api: {}\n' > docker-compose.imap.yml
  exit 0
fi

{
  echo "# GENERATED by imap-override.sh — do not edit; regenerated on every reset with the current cert."
  echo "services:"
  echo "  api:"
  echo "    ports:"
  echo '      - "993:9993"'
  echo "    environment:"
  echo '      Imap__Enabled: "true"'
  echo '      Imap__TlsPort: "9993"'
  echo "      Imap__PublicHost: \"$DOMAIN\""
  echo "      Imap__CertificatePem: |"
  sed 's/^/        /' "$CERT"
  echo "      Imap__CertificateKeyPem: |"
  sed 's/^/        /' "$KEY"
} > docker-compose.imap.yml

echo "IMAP override written from $CERT"
